FROM ghcr.io/m1k1o/neko/chromium:latest

ENV NEKO_DESKTOP_SCREEN=1024x576
ENV NEKO_MEMBER_PROVIDER=multiuser
ENV NEKO_MEMBER_MULTIUSER_USER_PASSWORD=user
ENV NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD=admin

ENV NEKO_SERVER_BIND=0.0.0.0:8080

ENV NEKO_WEBRTC_ICELITE=true
ENV NEKO_WEBRTC_TCPMUX=8080
ENV NEKO_WEBRTC_UDPMUX=8080

ENV NEKO_WEBRTC_ICESERVERS=[{"urls":["stun:stun.l.google.com:19302"]}]

EXPOSE 8080
